name: CICD for Youtube

on:
  push:
    branches:
        - main

jobs: 

  depoly:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: reddiprasad72/CICD-Youtube@main
      
              
            
