name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: reddiprasad72/CICD-Youtube@main
      # If you make changes on your fork, be sure not leave @latest as tag!
        with:
          # Your GitHub token
          token: ${{ secrets.MY_TOKEN }}
