name: CICD for Youtube

on:
  push:
    branches:
        - main

jobs: 

  depoly:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
               cd /var/www/
               sudo git clone -b develop https://RPrasad72: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@github.com/bluboygames/backend-api.git
               sudo apt-get update
               sudo apt-get install apache2 -y
               sudo add-apt-repository ppa:ondrej/php
               sudo apt-get update
               sudo apt-get install -y php7.4
            



